package com.henu.bean;

import java.util.List;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.CategoryId
     *
     * @mbggenerated
     */

    private Integer categoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.CategoryName
     *
     * @mbggenerated
     */
    private String categoryname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.ParentId
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.Level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.url
     *
     * @mbggenerated
     */
    private String url;

    public List<Category> categoryChilds;

    public List<Category> getCategoryChilds() {
        return categoryChilds;
    }

    public void setCategoryChilds(List<Category> categoryChilds) {
        this.categoryChilds = categoryChilds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.CategoryId
     *
     * @return the value of category.CategoryId
     *
     * @mbggenerated
     */
    public Integer getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.CategoryId
     *
     * @param categoryid the value for category.CategoryId
     *
     * @mbggenerated
     */
    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.CategoryName
     *
     * @return the value of category.CategoryName
     *
     * @mbggenerated
     */
    public String getCategoryname() {
        return categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.CategoryName
     *
     * @param categoryname the value for category.CategoryName
     *
     * @mbggenerated
     */
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname == null ? null : categoryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.ParentId
     *
     * @return the value of category.ParentId
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.ParentId
     *
     * @param parentid the value for category.ParentId
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.Level
     *
     * @return the value of category.Level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.Level
     *
     * @param level the value for category.Level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.url
     *
     * @return the value of category.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.url
     *
     * @param url the value for category.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}