package com.henu.bean;

import java.util.Date;
import java.util.List;

public class HuiFu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifu.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifu.TieZiId
     *
     * @mbggenerated
     */
    private Integer tieziid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifu.LouCeng
     *
     * @mbggenerated
     */
    private String louceng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifu.UserPetName
     *
     * @mbggenerated
     */
    private String userpetname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifu.Content
     *
     * @mbggenerated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifu.Time
     *
     * @mbggenerated
     */
    private Date time;

    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifu.href
     *
     * @mbggenerated
     */
    private String href;

    private List<PingLun> pingLunList;

    public List<PingLun> getPingLunList() {
        return pingLunList;
    }

    public void setPingLunList(List<PingLun> pingLunList) {
        this.pingLunList = pingLunList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifu.Id
     *
     * @return the value of huifu.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifu.Id
     *
     * @param id the value for huifu.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifu.TieZiId
     *
     * @return the value of huifu.TieZiId
     *
     * @mbggenerated
     */
    public Integer getTieziid() {
        return tieziid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifu.TieZiId
     *
     * @param tieziid the value for huifu.TieZiId
     *
     * @mbggenerated
     */
    public void setTieziid(Integer tieziid) {
        this.tieziid = tieziid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifu.LouCeng
     *
     * @return the value of huifu.LouCeng
     *
     * @mbggenerated
     */
    public String getLouceng() {
        return louceng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifu.LouCeng
     *
     * @param louceng the value for huifu.LouCeng
     *
     * @mbggenerated
     */
    public void setLouceng(String louceng) {
        this.louceng = louceng == null ? null : louceng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifu.UserPetName
     *
     * @return the value of huifu.UserPetName
     *
     * @mbggenerated
     */
    public String getUserpetname() {
        return userpetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifu.UserPetName
     *
     * @param userpetname the value for huifu.UserPetName
     *
     * @mbggenerated
     */
    public void setUserpetname(String userpetname) {
        this.userpetname = userpetname == null ? null : userpetname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifu.Content
     *
     * @return the value of huifu.Content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifu.Content
     *
     * @param content the value for huifu.Content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifu.Time
     *
     * @return the value of huifu.Time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifu.Time
     *
     * @param time the value for huifu.Time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifu.href
     *
     * @return the value of huifu.href
     *
     * @mbggenerated
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifu.href
     *
     * @param href the value for huifu.href
     *
     * @mbggenerated
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }
}