package com.henu.bean;

import java.util.Date;

public class PingLun {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pinglun.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pinglun.HuiFuId
     *
     * @mbggenerated
     */
    private Integer huifuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pinglun.Context
     *
     * @mbggenerated
     */
    private String context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pinglun.Time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pinglun.UserPetName
     *
     * @mbggenerated
     */
    private String userpetname;

    private User user;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pinglun.id
     *
     * @return the value of pinglun.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pinglun.id
     *
     * @param id the value for pinglun.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pinglun.HuiFuId
     *
     * @return the value of pinglun.HuiFuId
     *
     * @mbggenerated
     */
    public Integer getHuifuid() {
        return huifuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pinglun.HuiFuId
     *
     * @param huifuid the value for pinglun.HuiFuId
     *
     * @mbggenerated
     */
    public void setHuifuid(Integer huifuid) {
        this.huifuid = huifuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pinglun.Context
     *
     * @return the value of pinglun.Context
     *
     * @mbggenerated
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pinglun.Context
     *
     * @param context the value for pinglun.Context
     *
     * @mbggenerated
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pinglun.Time
     *
     * @return the value of pinglun.Time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pinglun.Time
     *
     * @param time the value for pinglun.Time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pinglun.UserPetName
     *
     * @return the value of pinglun.UserPetName
     *
     * @mbggenerated
     */
    public String getUserpetname() {
        return userpetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pinglun.UserPetName
     *
     * @param userpetname the value for pinglun.UserPetName
     *
     * @mbggenerated
     */
    public void setUserpetname(String userpetname) {
        this.userpetname = userpetname == null ? null : userpetname.trim();
    }
}