package com.henu.bean;

public class ShouCangKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoucang.UserName
     *
     * @mbggenerated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoucang.TieZiId
     *
     * @mbggenerated
     */
    private Integer tieziid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoucang.UserName
     *
     * @return the value of shoucang.UserName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoucang.UserName
     *
     * @param username the value for shoucang.UserName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoucang.TieZiId
     *
     * @return the value of shoucang.TieZiId
     *
     * @mbggenerated
     */
    public Integer getTieziid() {
        return tieziid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoucang.TieZiId
     *
     * @param tieziid the value for shoucang.TieZiId
     *
     * @mbggenerated
     */
    public void setTieziid(Integer tieziid) {
        this.tieziid = tieziid;
    }
}