package com.henu.bean;

public class TieBa {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tieba.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tieba.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tieba.NameIndex
     *
     * @mbggenerated
     */
    private String nameindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tieba.CategoryId
     *
     * @mbggenerated
     */
    private Integer categoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tieba.Signature
     *
     * @mbggenerated
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tieba.HeadImgUrl
     *
     * @mbggenerated
     */
    private String headimgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tieba.href
     *
     * @mbggenerated
     */
    private String href;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tieba.id
     *
     * @return the value of tieba.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tieba.id
     *
     * @param id the value for tieba.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tieba.Name
     *
     * @return the value of tieba.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tieba.Name
     *
     * @param name the value for tieba.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tieba.NameIndex
     *
     * @return the value of tieba.NameIndex
     *
     * @mbggenerated
     */
    public String getNameindex() {
        return nameindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tieba.NameIndex
     *
     * @param nameindex the value for tieba.NameIndex
     *
     * @mbggenerated
     */
    public void setNameindex(String nameindex) {
        this.nameindex = nameindex == null ? null : nameindex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tieba.CategoryId
     *
     * @return the value of tieba.CategoryId
     *
     * @mbggenerated
     */
    public Integer getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tieba.CategoryId
     *
     * @param categoryid the value for tieba.CategoryId
     *
     * @mbggenerated
     */
    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tieba.Signature
     *
     * @return the value of tieba.Signature
     *
     * @mbggenerated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tieba.Signature
     *
     * @param signature the value for tieba.Signature
     *
     * @mbggenerated
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tieba.HeadImgUrl
     *
     * @return the value of tieba.HeadImgUrl
     *
     * @mbggenerated
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tieba.HeadImgUrl
     *
     * @param headimgurl the value for tieba.HeadImgUrl
     *
     * @mbggenerated
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tieba.href
     *
     * @return the value of tieba.href
     *
     * @mbggenerated
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tieba.href
     *
     * @param href the value for tieba.href
     *
     * @mbggenerated
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }
}