package com.henu.bean;

public class UserTiebaKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tieba.UserName
     *
     * @mbggenerated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tieba.TieBaId
     *
     * @mbggenerated
     */
    private Integer tiebaid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tieba.UserName
     *
     * @return the value of user_tieba.UserName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tieba.UserName
     *
     * @param username the value for user_tieba.UserName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tieba.TieBaId
     *
     * @return the value of user_tieba.TieBaId
     *
     * @mbggenerated
     */
    public Integer getTiebaid() {
        return tiebaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tieba.TieBaId
     *
     * @param tiebaid the value for user_tieba.TieBaId
     *
     * @mbggenerated
     */
    public void setTiebaid(Integer tiebaid) {
        this.tiebaid = tiebaid;
    }
}