package com.henu.bean;

import java.util.Date;

public class UserTieba extends UserTiebaKey {
    private String tiebaName;

    public String getTiebaName() {
        return tiebaName;
    }

    public void setTiebaName(String tiebaName) {
        this.tiebaName = tiebaName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tieba.Level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tieba.IsAdmin
     *
     * @mbggenerated
     */
    private Integer isadmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tieba.AdminLevel
     *
     * @mbggenerated
     */
    private Integer adminlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tieba.JingYan
     *
     * @mbggenerated
     */
    private Integer jingyan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tieba.IsQianDao
     *
     * @mbggenerated
     */
    private Integer isqiandao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tieba.IsFollow
     *
     * @mbggenerated
     */
    private Integer isfollow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tieba.FollowTime
     *
     * @mbggenerated
     */
    private Date followtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tieba.LouQianStrings
     *
     * @mbggenerated
     */
    private String louqianstrings;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tieba.Level
     *
     * @return the value of user_tieba.Level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tieba.Level
     *
     * @param level the value for user_tieba.Level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tieba.IsAdmin
     *
     * @return the value of user_tieba.IsAdmin
     *
     * @mbggenerated
     */
    public Integer getIsadmin() {
        return isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tieba.IsAdmin
     *
     * @param isadmin the value for user_tieba.IsAdmin
     *
     * @mbggenerated
     */
    public void setIsadmin(Integer isadmin) {
        this.isadmin = isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tieba.AdminLevel
     *
     * @return the value of user_tieba.AdminLevel
     *
     * @mbggenerated
     */
    public Integer getAdminlevel() {
        return adminlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tieba.AdminLevel
     *
     * @param adminlevel the value for user_tieba.AdminLevel
     *
     * @mbggenerated
     */
    public void setAdminlevel(Integer adminlevel) {
        this.adminlevel = adminlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tieba.JingYan
     *
     * @return the value of user_tieba.JingYan
     *
     * @mbggenerated
     */
    public Integer getJingyan() {
        return jingyan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tieba.JingYan
     *
     * @param jingyan the value for user_tieba.JingYan
     *
     * @mbggenerated
     */
    public void setJingyan(Integer jingyan) {
        this.jingyan = jingyan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tieba.IsQianDao
     *
     * @return the value of user_tieba.IsQianDao
     *
     * @mbggenerated
     */
    public Integer getIsqiandao() {
        return isqiandao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tieba.IsQianDao
     *
     * @param isqiandao the value for user_tieba.IsQianDao
     *
     * @mbggenerated
     */
    public void setIsqiandao(Integer isqiandao) {
        this.isqiandao = isqiandao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tieba.IsFollow
     *
     * @return the value of user_tieba.IsFollow
     *
     * @mbggenerated
     */
    public Integer getIsfollow() {
        return isfollow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tieba.IsFollow
     *
     * @param isfollow the value for user_tieba.IsFollow
     *
     * @mbggenerated
     */
    public void setIsfollow(Integer isfollow) {
        this.isfollow = isfollow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tieba.FollowTime
     *
     * @return the value of user_tieba.FollowTime
     *
     * @mbggenerated
     */
    public Date getFollowtime() {
        return followtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tieba.FollowTime
     *
     * @param followtime the value for user_tieba.FollowTime
     *
     * @mbggenerated
     */
    public void setFollowtime(Date followtime) {
        this.followtime = followtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tieba.LouQianStrings
     *
     * @return the value of user_tieba.LouQianStrings
     *
     * @mbggenerated
     */
    public String getLouqianstrings() {
        return louqianstrings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tieba.LouQianStrings
     *
     * @param louqianstrings the value for user_tieba.LouQianStrings
     *
     * @mbggenerated
     */
    public void setLouqianstrings(String louqianstrings) {
        this.louqianstrings = louqianstrings == null ? null : louqianstrings.trim();
    }
}