package com.henu.bean;

public class UserSetting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersetting.UserName
     *
     * @mbggenerated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersetting.secret
     *
     * @mbggenerated
     */
    private Integer secret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersetting.NewFans
     *
     * @mbggenerated
     */
    private Integer newfans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersetting.NewAssess
     *
     * @mbggenerated
     */
    private Integer newassess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersetting.NewAnima
     *
     * @mbggenerated
     */
    private Integer newanima;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersetting.NewAnswer
     *
     * @mbggenerated
     */
    private Integer newanswer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersetting.AtMe
     *
     * @mbggenerated
     */
    private Integer atme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersetting.Collect
     *
     * @mbggenerated
     */
    private Integer collect;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersetting.UserName
     *
     * @return the value of usersetting.UserName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersetting.UserName
     *
     * @param username the value for usersetting.UserName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersetting.secret
     *
     * @return the value of usersetting.secret
     *
     * @mbggenerated
     */
    public Integer getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersetting.secret
     *
     * @param secret the value for usersetting.secret
     *
     * @mbggenerated
     */
    public void setSecret(Integer secret) {
        this.secret = secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersetting.NewFans
     *
     * @return the value of usersetting.NewFans
     *
     * @mbggenerated
     */
    public Integer getNewfans() {
        return newfans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersetting.NewFans
     *
     * @param newfans the value for usersetting.NewFans
     *
     * @mbggenerated
     */
    public void setNewfans(Integer newfans) {
        this.newfans = newfans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersetting.NewAssess
     *
     * @return the value of usersetting.NewAssess
     *
     * @mbggenerated
     */
    public Integer getNewassess() {
        return newassess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersetting.NewAssess
     *
     * @param newassess the value for usersetting.NewAssess
     *
     * @mbggenerated
     */
    public void setNewassess(Integer newassess) {
        this.newassess = newassess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersetting.NewAnima
     *
     * @return the value of usersetting.NewAnima
     *
     * @mbggenerated
     */
    public Integer getNewanima() {
        return newanima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersetting.NewAnima
     *
     * @param newanima the value for usersetting.NewAnima
     *
     * @mbggenerated
     */
    public void setNewanima(Integer newanima) {
        this.newanima = newanima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersetting.NewAnswer
     *
     * @return the value of usersetting.NewAnswer
     *
     * @mbggenerated
     */
    public Integer getNewanswer() {
        return newanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersetting.NewAnswer
     *
     * @param newanswer the value for usersetting.NewAnswer
     *
     * @mbggenerated
     */
    public void setNewanswer(Integer newanswer) {
        this.newanswer = newanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersetting.AtMe
     *
     * @return the value of usersetting.AtMe
     *
     * @mbggenerated
     */
    public Integer getAtme() {
        return atme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersetting.AtMe
     *
     * @param atme the value for usersetting.AtMe
     *
     * @mbggenerated
     */
    public void setAtme(Integer atme) {
        this.atme = atme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersetting.Collect
     *
     * @return the value of usersetting.Collect
     *
     * @mbggenerated
     */
    public Integer getCollect() {
        return collect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersetting.Collect
     *
     * @param collect the value for usersetting.Collect
     *
     * @mbggenerated
     */
    public void setCollect(Integer collect) {
        this.collect = collect;
    }
}