package com.henu.bean;

public class userUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_user.userName1
     *
     * @mbggenerated
     */
    private String username1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_user.userName2
     *
     * @mbggenerated
     */
    private String username2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_user.guanzhu
     *
     * @mbggenerated
     */
    private Integer guanzhu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_user.ChatRecord
     *
     * @mbggenerated
     */
    private String chatrecord;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_user.userName1
     *
     * @return the value of user_user.userName1
     *
     * @mbggenerated
     */
    public String getUsername1() {
        return username1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_user.userName1
     *
     * @param username1 the value for user_user.userName1
     *
     * @mbggenerated
     */
    public void setUsername1(String username1) {
        this.username1 = username1 == null ? null : username1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_user.userName2
     *
     * @return the value of user_user.userName2
     *
     * @mbggenerated
     */
    public String getUsername2() {
        return username2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_user.userName2
     *
     * @param username2 the value for user_user.userName2
     *
     * @mbggenerated
     */
    public void setUsername2(String username2) {
        this.username2 = username2 == null ? null : username2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_user.guanzhu
     *
     * @return the value of user_user.guanzhu
     *
     * @mbggenerated
     */
    public Integer getGuanzhu() {
        return guanzhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_user.guanzhu
     *
     * @param guanzhu the value for user_user.guanzhu
     *
     * @mbggenerated
     */
    public void setGuanzhu(Integer guanzhu) {
        this.guanzhu = guanzhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_user.ChatRecord
     *
     * @return the value of user_user.ChatRecord
     *
     * @mbggenerated
     */
    public String getChatrecord() {
        return chatrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_user.ChatRecord
     *
     * @param chatrecord the value for user_user.ChatRecord
     *
     * @mbggenerated
     */
    public void setChatrecord(String chatrecord) {
        this.chatrecord = chatrecord == null ? null : chatrecord.trim();
    }
}