package com.henu.dao;

import com.henu.bean.Category;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

@Mapper
public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer categoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated
     */
    int insert(Category record);
    @Select("select count(1) from Category where categoryname=#{name}")
    int selectByName(String name);
    @Select("select * from category where level =#{level}")
    List<Category> selectByLevel(int level);


    @Update("update category set parentId = #{Pid}")
    int updatePid(int Pid);

    @Select("select * from Category where categoryname=#{name}")
    List<Category> selectCategoryByName(String name);
    @Select("select * from category where parentId=#{id}")
    List<Category> selectByPid(Integer id);

    @Select("select * from category where parentId=#{id} limit #{beginindex},#{OnePageCount}")
    List<Category> selectByPidLimit(@Param("id ")Integer id, @Param("beginindex")int beginindex, @Param("OnePageCount")int OnePageCount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated
     */
    Category selectByPrimaryKey(Integer categoryid);
    @Select("select * from category where categoryid not in(select categoryId from tieba) and level='3'")
    List<Category> selectCategoryNoTieBa();


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Category record);
}