package com.henu.dao;

import com.henu.bean.HuiFu;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface HuiFuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbggenerated
     */
    int insert(HuiFu record);

    @Select("select * from huifu where TieZiId =#{TieZiId} and LouCeng = #{louceng}")
    HuiFu selectByTieZiIdLouCeng(@Param("TieZiId")int TieZiId,@Param("louceng")String louceng);

    @Select("select * from huifu where TieZiId =#{TieZiId} limit #{startIndex},#{pageSum}")
    List<HuiFu> selectByTieZiId(@Param("TieZiId")String TieZiId,@Param("startIndex")int startIndex,@Param("pageSum")int pageSum);

    @Select("select count(1) from huifu where TieZiId =#{TieZiId}")
    int selectCountByTieZiId(@Param("TieZiId")String TieZiId);

    @Select("select max(louceng) from huifu where TieZiId =#{TieZiId}")
    int selectLoucengByTieZiId(@Param("TieZiId")String TieZiId);
    @Select("select * from huifu where userPetName =#{userPetName}")
    List<HuiFu> selectHuifuByPetName(@Param("userPetName")String userPetName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbggenerated
     */
    int insertSelective(HuiFu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbggenerated
     */
    HuiFu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HuiFu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HuiFu record);
}