package com.henu.dao;

import com.henu.bean.PingLun;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface PingLunMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pinglun
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    @Select("select * from pinglun where huifuid = #{huifuId}")
    List<PingLun> selectPingLunByHuiFuId(Integer huifuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pinglun
     *
     * @mbggenerated
     */
    int insert(PingLun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pinglun
     *
     * @mbggenerated
     */
    int insertSelective(PingLun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pinglun
     *
     * @mbggenerated
     */
    PingLun selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pinglun
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PingLun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pinglun
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PingLun record);
}