package com.henu.dao;

import com.henu.bean.ShouCang;
import com.henu.bean.ShouCangKey;

public interface ShouCangMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoucang
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ShouCangKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoucang
     *
     * @mbggenerated
     */
    int insert(ShouCang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoucang
     *
     * @mbggenerated
     */
    int insertSelective(ShouCang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoucang
     *
     * @mbggenerated
     */
    ShouCang selectByPrimaryKey(ShouCangKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoucang
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShouCang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoucang
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShouCang record);
}