package com.henu.dao;

import com.henu.bean.Category;
import com.henu.bean.TieBa;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface TieBaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tieba
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    //查询已经爬取的贴吧
    @Select("select * from tieba")
    List<TieBa> selectAllTieBa();

    @Select("select * from tieba limit #{startindex},20")
    List<TieBa> selectTieBaPage(int startindex);
    @Select("select * from tieba where name=#{name}")
    TieBa selectByKey(String name);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tieba
     *
     * @mbggenerated
     */
    int insert(TieBa record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tieba
     *
     * @mbggenerated
     */
    int insertSelective(TieBa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tieba
     *
     * @mbggenerated
     */
    TieBa selectByPrimaryKey(Integer id);
    @Select("select * from tieba where id not in(select tiebaid from tiezi)")
    List<TieBa> selectNoCrawlerTieBa();

    @Select("select * from tieba where Categoryid =#{Categoryid}")
    TieBa selectTieBaByCagegoryId(Integer Categoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tieba
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TieBa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tieba
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TieBa record);
}