package com.henu.dao;

import com.henu.bean.TieZi;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Service;

import javax.annotation.Generated;
import java.util.List;

@Mapper
public interface TieZiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiezi
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiezi
     *
     * @mbggenerated
     */
    int insert(TieZi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiezi
     *
     * @mbggenerated
     */
    int insertSelective(TieZi record);

    int insertBatch(List<TieZi> tiezilist);

    @Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "Id")
    @Insert("insert into tiezi(TieBaId,Title,UserPetName,CteateTime) values(#{tiezi.tiebaid},#{tiezi.title},#{tiezi.userpetname},#{tiezi.cteatetime})")
    int insertOneTieZi(@Param("tiezi")TieZi tiezi);

    @Select("select * from tiezi where Title like #{title} and UserPetName like #{petname}")
    TieZi selectByTitleUserPetName(@Param("title") String title, @Param("petname") String petname);

    @Select("select * from tiezi")
    List<TieZi> selectAllTieZi();

    @Select("select * from tiezi where id not in (select TieZiId from huifu)")
    List<TieZi> selectNoCrawlerTieZi();

    @Select("select * from tiezi where tiebaid = #{TieBaId} order by sort desc,cteatetime desc limit #{startIndex},#{pageSum}")
    List<TieZi> selectTieZiByTieBaId(@Param("TieBaId")int TieBaId,@Param("startIndex")int startIndex,@Param("pageSum")int pageSum);

    @Select("select * from tiezi where tiebaid = #{TieBaId} and isjingpin=#{Type} order by sort desc,cteatetime desc limit #{startIndex},#{pageSum} ")
    List<TieZi> selectTypeTieZiByTieBaId(@Param("TieBaId")int TieBaId,@Param("Type")int type,@Param("startIndex")int startIndex,@Param("pageSum")int pageSum);



    @Select("select * from tiezi where title = #{tiezi.title} and userpetname = #{tiezi.userpetname}")
    TieZi selectTieZiByTitleAndUserPetName(@Param("tiezi")TieZi tiezi);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiezi
     *
     * @mbggenerated
     */
    TieZi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiezi
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TieZi record);
    @Select("select count(1) from tiezi where tiebaid = #{TieBaId}")
    int selectCountById(@Param("TieBaId") int TieBaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiezi
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TieZi record);
}