package com.henu.dao;

import com.henu.bean.UserSetting;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersetting
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersetting
     *
     * @mbggenerated
     */
    int insert(UserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersetting
     *
     * @mbggenerated
     */
    int insertSelective(UserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersetting
     *
     * @mbggenerated
     */
    UserSetting selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersetting
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersetting
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserSetting record);
}