package com.henu.dao;

import com.henu.bean.userTieZi;

public interface userTieZiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tiezi
     *
     * @mbggenerated
     */
    int insert(userTieZi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tiezi
     *
     * @mbggenerated
     */
    int insertSelective(userTieZi record);
}