package com.henu.dao;

import com.henu.bean.userUser;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

@Mapper
public interface userUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    int insert(userUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    int insertSelective(userUser record);
    @Select("select * from user_user where username1 = #{username1} and guanzhu = 1")
    List<userUser> selectFriend(@Param("username1") String username1);
    @Select("select * from user_user where username1 = #{username1} and username2 = #{username2}")
    userUser selectByUsername1And2(@Param("username1") String username1, @Param("username2")String username2);
    @Update("update user_user set guanzhu=#{type} where username1 = #{username1} and username2 = #{username2}")
    int updateguanzhu(@Param("username1") String username1, @Param("username2")String username2,@Param("type") int type);
}